apiVersion: v1
kind: Service
metadata:
  name: whiteboard-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: whiteboard
  ports:
    - port: 80
      targetPort: 8080
