apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whiteboard
  template:
    metadata:
      labels:
        app: whiteboard
    spec:
      containers:
        - name: whiteboard
          image: 434439813077.dkr.ecr.eu-west-2.amazonaws.com/whiteboard-aws:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
